#include "AetherVGUI.h"
#include <stdlib.h>
#include <string.h>
struct aether_vgui { aether_vgui_panel_t panels[AETHER_VGUI_MAX_PANELS]; bool used[AETHER_VGUI_MAX_PANELS]; u32 count; u32 focus; };
static bool valid(const aether_vgui_t*v,u32 id){return v&&id<AETHER_VGUI_MAX_PANELS&&v->used[id];}
aether_vgui_t*aether_vgui_create(void){ aether_vgui_t*v=calloc(1,sizeof*v); if(!v)return NULL; u32 root=0; v->used[root]=true; v->count=1; v->panels[root].id=0; v->panels[root].type=AETHER_VGUI_PANEL; v->panels[root].visible=true; v->panels[root].enabled=true; aether_str_copy(v->panels[root].name,sizeof v->panels[root].name,"Root"); v->focus=0; return v; }
void aether_vgui_destroy(aether_vgui_t*v){free(v);}
u32 aether_vgui_add(aether_vgui_t*v,aether_vgui_type_t type,u32 parent,const char*name,const char*text){if(!v||!valid(v,parent))return UINT32_MAX;u32 id=UINT32_MAX;for(u32 i=1;i<AETHER_VGUI_MAX_PANELS;i++)if(!v->used[i]){id=i;break;}if(id==UINT32_MAX)return id;aether_vgui_panel_t*p=&v->panels[id];memset(p,0,sizeof*p);p->id=id;p->type=type;p->visible=true;p->enabled=true;p->parent_id=parent;p->bounds=(aether_vgui_rect_t){0,0,1,0.06f};aether_str_copy(p->name,sizeof p->name,name?name:"");aether_str_copy(p->text,sizeof p->text,text?text:"");v->used[id]=true;v->count++;aether_vgui_panel_t*pp=&v->panels[parent];if(pp->child_count<AETHER_VGUI_MAX_CHILDREN)pp->children[pp->child_count++]=id;return id;}
aether_vgui_panel_t*aether_vgui_panel(aether_vgui_t*v,u32 id){return valid(v,id)?&v->panels[id]:NULL;}
aether_result_t aether_vgui_remove(aether_vgui_t*v,u32 id){if(!valid(v,id)||id==0)return AETHER_ERR_INVALID_ARG;aether_vgui_panel_t*p=&v->panels[id];if(valid(v,p->parent_id)){aether_vgui_panel_t*pp=&v->panels[p->parent_id];for(u32 i=0;i<pp->child_count;i++)if(pp->children[i]==id){memmove(&pp->children[i],&pp->children[i+1],(pp->child_count-i-1)*sizeof(pp->children[0]));pp->child_count--;break;}}v->used[id]=false;memset(p,0,sizeof*p);if(v->count)v->count--;if(v->focus==id)v->focus=0;return AETHER_OK;}
aether_result_t aether_vgui_set_visible(aether_vgui_t*v,u32 id,bool x){if(!valid(v,id))return AETHER_ERR_INVALID_ARG;v->panels[id].visible=x;return AETHER_OK;}
aether_result_t aether_vgui_set_bounds(aether_vgui_t*v,u32 id,f32 x,f32 y,f32 w,f32 h){if(!valid(v,id)||w<0||h<0)return AETHER_ERR_INVALID_ARG;v->panels[id].bounds=(aether_vgui_rect_t){x,y,w,h};return AETHER_OK;}
aether_result_t aether_vgui_set_text(aether_vgui_t*v,u32 id,const char*t){if(!valid(v,id)||!t)return AETHER_ERR_INVALID_ARG;aether_str_copy(v->panels[id].text,sizeof v->panels[id].text,t);return AETHER_OK;}
aether_result_t aether_vgui_set_action(aether_vgui_t*v,u32 id,aether_vgui_action_fn fn,void*u){if(!valid(v,id))return AETHER_ERR_INVALID_ARG;v->panels[id].action=fn;v->panels[id].action_user=u;return AETHER_OK;}
aether_result_t aether_vgui_activate(aether_vgui_t*v,u32 id){if(!valid(v,id))return AETHER_ERR_INVALID_ARG;aether_vgui_panel_t*p=&v->panels[id];if(!p->enabled||!p->visible)return AETHER_ERR_STATE;if(p->type==AETHER_VGUI_CHECKBOX)p->checked=!p->checked;if(p->type==AETHER_VGUI_SLIDER){f32 step=(p->slider_max-p->slider_min)*0.1f;p->slider_value+=step;if(p->slider_value>p->slider_max)p->slider_value=p->slider_min;}if(p->action)p->action(p,p->action_user);return AETHER_OK;}
aether_result_t aether_vgui_navigate(aether_vgui_t*v,u32 parent,i32 dir){if(!valid(v,parent)||dir==0)return AETHER_ERR_INVALID_ARG;aether_vgui_panel_t*pp=&v->panels[parent];if(!pp->child_count)return AETHER_ERR_NOT_FOUND;i32 cur=-1;for(u32 i=0;i<pp->child_count;i++)if(pp->children[i]==v->focus){cur=(i32)i;break;}if(cur<0)cur=(dir>0)?-1:(i32)pp->child_count;for(u32 n=0;n<pp->child_count;n++){cur+=dir;if(cur<0)cur=(i32)pp->child_count-1;if(cur>=(i32)pp->child_count)cur=0;u32 id=pp->children[cur];if(valid(v,id)&&v->panels[id].visible&&v->panels[id].enabled&&v->panels[id].type!=AETHER_VGUI_LABEL){v->focus=id;v->panels[id].focused=true;return AETHER_OK;}}return AETHER_ERR_NOT_FOUND;}
u32 aether_vgui_child_count(const aether_vgui_t*v,u32 parent){return valid(v,parent)?v->panels[parent].child_count:0;}
const aether_vgui_panel_t*aether_vgui_child_at(const aether_vgui_t*v,u32 parent,u32 i){if(!valid(v,parent)||i>=v->panels[parent].child_count)return NULL;u32 id=v->panels[parent].children[i];return valid(v,id)?&v->panels[id]:NULL;}
void aether_vgui_draw(const aether_vgui_t*v,void*ctx){(void)ctx;if(!v)return;for(u32 i=0;i<AETHER_VGUI_MAX_PANELS;i++)if(v->used[i]&&v->panels[i].visible){const aether_vgui_panel_t*p=&v->panels[i];aether_log(AETHER_LOG_TRACE,"vgui","%s: %s",p->name,p->text);}}
