#include "AetherPathfinding.h"
#include <string.h>
#include <math.h>
static f32 d2(aether_vec3_t a,aether_vec3_t b){f32 x=a.x-b.x,y=a.y-b.y,z=a.z-b.z;return x*x+y*y+z*z;}
void aether_path_graph_init(aether_path_graph_t*g){if(g)memset(g,0,sizeof*g);}
i32 aether_path_add_node(aether_path_graph_t*g,aether_vec3_t p){if(!g||g->count>=AETHER_PATH_MAX_NODES)return -1;u32 i=g->count++;g->nodes[i].id=i;g->nodes[i].pos=p;g->nodes[i].active=true;return (i32)i;}
bool aether_path_connect(aether_path_graph_t*g,u32 a,u32 b,bool bi){if(!g||a>=g->count||b>=g->count||!g->nodes[a].active||!g->nodes[b].active)return false;for(int pass=0;pass<(bi?2:1);pass++){u32 x=pass?b:a,y=pass?a:b;bool exists=false;for(u32 j=0;j<g->nodes[x].neighbor_count;j++)if(g->nodes[x].neighbors[j]==y)exists=true;if(!exists){if(g->nodes[x].neighbor_count>=AETHER_PATH_MAX_NEIGHBORS)return false;g->nodes[x].neighbors[g->nodes[x].neighbor_count++]=y;}}return true;}
i32 aether_path_find(const aether_path_graph_t*g,u32 s,u32 goal,u32*out,u32 max){if(!g||!out||!max||s>=g->count||goal>=g->count)return -1;static f32 cost[AETHER_PATH_MAX_NODES],score[AETHER_PATH_MAX_NODES];static i32 parent[AETHER_PATH_MAX_NODES];static bool open[AETHER_PATH_MAX_NODES],closed[AETHER_PATH_MAX_NODES];for(u32 i=0;i<g->count;i++){cost[i]=score[i]=INFINITY;parent[i]=-1;open[i]=closed[i]=false;}cost[s]=0;score[s]=sqrtf(d2(g->nodes[s].pos,g->nodes[goal].pos));open[s]=true;for(u32 step=0;step<g->count;step++){i32 cur=-1;for(u32 i=0;i<g->count;i++)if(open[i]&&!closed[i]&&(cur<0||score[i]<score[cur]))cur=(i32)i;if(cur<0)break;if((u32)cur==goal){u32 n=0;for(i32 x=cur;x>=0&&n<max;x=parent[x])out[n++]=(u32)x;for(u32 i=0;i<n/2;i++){u32 t=out[i];out[i]=out[n-1-i];out[n-1-i]=t;}return (i32)n;}open[cur]=false;closed[cur]=true;const aether_path_node_t*n=&g->nodes[cur];for(u32 j=0;j<n->neighbor_count;j++){u32 v=n->neighbors[j];if(closed[v]||!g->nodes[v].active)continue;f32 ng=cost[cur]+sqrtf(d2(n->pos,g->nodes[v].pos));if(!open[v]||ng<cost[v]){parent[v]=cur;cost[v]=ng;score[v]=ng+sqrtf(d2(g->nodes[v].pos,g->nodes[goal].pos));open[v]=true;}}}return -1;}
i32 aether_path_find_nearest(const aether_path_graph_t*g,aether_vec3_t p,f32 maxd){if(!g)return -1;f32 best=maxd*maxd; i32 id=-1;for(u32 i=0;i<g->count;i++)if(g->nodes[i].active){f32 x=d2(g->nodes[i].pos,p);if(x<=best){best=x;id=(i32)i;}}return id;}
